### PR TITLE
Create awesome-asgardia

### PR DESCRIPTION
**Pull request by MeTaNoV**

### CODE REVIEW

**Comment by MeTaNoV** [comment]
who has write access currently? I'd like to have some also!

**Comment by ANLevant** [comment]
Aong is actually managing permissions, ask him for a permision, by the way, we have a slack communication channel as well, leave me your email so I can invite you

**Comment by MeTaNoV** [comment]
pascal.gula@gmail.com good to know! :)

**Comment by MeTaNoV** [comment]
@yxwzaxns ? :)

**Comment by yxwzaxns** [comment]
It's very nice, thx :)

**Comment by Taehupo** [comment]
Hello everyone !

**Comment by yxwzaxns** [comment]
@Taehupo Are you interested in contribute to us?

**Comment by Taehupo** [comment]
Well yes ^^  otherwise I wouldn't be here =P

**Comment by yxwzaxns** [comment]
@Taehupo check out your email :)

**Comment by Taehupo** [comment]
Just so you know, I'm know C++, I'm able to manage a DB(Postgres or MySQL), and I have bases in PHP ^^

**Comment by yxwzaxns** [comment]
@Taehupo give your email to me, I invite you to join slack group

**Comment by Taehupo** [comment]
uzumakigip@gmail.com there you go =D

**Comment by ANLevant** [comment]
@MeTaNoV Just invited you to the slack channel, also to all people her ein this thread, there's a repository where there's a project proposal for the Asgardia Social Network, feel free to check it out and make any modifications you feel it needs, the idea would be to buiñld a solid project proposal and then try to send it to Asgardia for liasing with them

**Comment by petrk94** [comment]
Hi,
I can HTML, Shell (bash), cmd (batch), C and C++ for Microcontrollers and Im learning python now.
You can checkout my repos :)

**Pull request merged**
